### ISSUE TITLE
installing error in 7th step

### ISSUE THREAD

**Issue by Malaka-S-Gunawardhana** [hanruihua/Turtlebot2_on_noetic#1]
_I am new to ROS and still learning. I face this error while installing process.
please help me with this.
Thank you!_ 
![Error](https://user-images.githubusercontent.com/94318477/141696094-e243be73-f113-4c1d-a2a5-ec14ecb35c76.png)

**Comment by hanruihua** [comment]
You can try to use this command to solve that:

sudo apt-get install pyqt5-dev-tools

**Comment by hanruihua** [comment]
You can try to use this command to solve that:

sudo apt-get install pyqt5-dev-tools

**Comment by Malaka-S-Gunawardhana** [comment]
> You can try to use this command to solve that:
> 
> sudo apt-get install pyqt5-dev-tools
