### ISSUE TITLE
Error when running "roslaunch turtlebot_teleop keyboard_teleop.launch "

### ISSUE THREAD

**Issue by Malaka-S-Gunawardhana** [hanruihua/Turtlebot2_on_noetic#2]
I am facing this error.
please help
Thank you!

process[turtlebot_teleop_keyboard-1]: started with pid [2770]
/usr/bin/env: ‘python’: No such file or directory
[turtlebot_teleop_keyboard-1] process has died [pid 2770, exit code 127, cmd /home/malaka/catkin_ws/src/Turtlebot_on_noetic/turtlebot/turtlebot_teleop/scripts/turtlebot_teleop_key turtlebot_teleop_keyboard/cmd_vel:=cmd_vel_mux/input/teleop __name:=turtlebot_teleop_keyboard __log:=/home/malaka/.ros/log/b9779876-471c-11ec-a8ac-951cdb29a7bf/turtlebot_teleop_keyboard-1.log].
log file: /home/malaka/.ros/log/b9779876-471c-11ec-a8ac-951cdb29a7bf/turtlebot_teleop_keyboard-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

![shot-2021-11-17_02-10-29](https://user-images.githubusercontent.com/94318477/142063376-951cb8da-95cd-4bc8-a542-474d622c4a6a.jpg)
.!

**Comment by hanruihua** [comment]
For ubuntu 20.04, you can try to use the following command to solve that:

sudo apt-get install python-is-python3

which ships a symlink to point the /usr/bin/python interpreter at the current default python

**Comment by Malaka-S-Gunawardhana** [comment]
**_Yes. It worked.
Thank you so much_ !!**
